import { useEffect, useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";

import {
  CheckCircle2,
  LoaderCircle,
  Sparkles,
  ShieldCheck,
  FileSearch,
  Database,
  ArrowRight,
} from "lucide-react";


const processingSteps = [
  {
    id: 1,
    title: "Extracting information",
    description:
      "Reading available product information and technical details.",
    icon: FileSearch,
  },
  {
    id: 2,
    title: "Normalizing attributes",
    description:
      "Converting product information into a consistent structure.",
    icon: Database,
  },
  {
    id: 3,
    title: "Enriching product data",
    description:
      "Building additional structured product attributes.",
    icon: Sparkles,
  },
  {
    id: 4,
    title: "Checking evidence",
    description:
      "Associating available information with traceable sources.",
    icon: FileSearch,
  },
  {
    id: 5,
    title: "Validating attributes",
    description:
      "Checking consistency and identifying uncertain values.",
    icon: ShieldCheck,
  },
  {
    id: 6,
    title: "Calculating confidence",
    description:
      "Assigning confidence scores to generated intelligence.",
    icon: ShieldCheck,
  },
];


function Processing() {
  const location = useLocation();
  const navigate = useNavigate();

  // Product already generated by backend
  const product = location.state?.product;

  const [currentStep, setCurrentStep] = useState(0);
  const [complete, setComplete] = useState(false);
  const [intelligence, setIntelligence] = useState(null);


  // =====================================================
  // PROCESS PRODUCT
  // =====================================================

  useEffect(() => {
    if (!product) {
      navigate("/add-product");
      return;
    }

    const timers = [];


    // =====================================================
    // SHOW PROCESSING ANIMATION
    // =====================================================

    processingSteps.forEach((_, index) => {
      const timer = setTimeout(() => {
        setCurrentStep(index + 1);
      }, (index + 1) * 900);

      timers.push(timer);
    });


    // =====================================================
    // COMPLETE PROCESSING
    // =====================================================

    const finishTimer = setTimeout(() => {

      // Backend has already generated the intelligence
      const generatedIntelligence = {
        ...product,

        // Make sure product has a unique ID
        id:
          product.id ||
          `product-${Date.now()}`,

        attributes:
          product.attributes || [],

        confidence:
          Number(product.confidence || 0),

        verifiedCount:
          Number(product.verifiedCount || 0),

        reviewCount:
          Number(product.reviewCount || 0),

        status:
          product.status ||
          "Needs Review",
      };


      // =====================================================
      // GET EXISTING PRODUCTS
      // =====================================================

      const savedProducts = JSON.parse(
        localStorage.getItem(
          "forgeintel_products"
        ) || "[]"
      );


      // =====================================================
      // CHECK IF PRODUCT ALREADY EXISTS
      // =====================================================

      const productExists = savedProducts.some(
        (item) =>
          String(item.id) ===
          String(generatedIntelligence.id)
      );


      let updatedProducts;


      // =====================================================
      // UPDATE OR ADD PRODUCT
      // =====================================================

      if (productExists) {
        updatedProducts = savedProducts.map(
          (item) =>
            String(item.id) ===
            String(generatedIntelligence.id)
              ? generatedIntelligence
              : item
        );
      } else {
        updatedProducts = [
          generatedIntelligence,
          ...savedProducts,
        ];
      }


      // =====================================================
      // SAVE ALL PRODUCTS
      // =====================================================

      localStorage.setItem(
        "forgeintel_products",
        JSON.stringify(updatedProducts)
      );


      // =====================================================
      // SAVE CURRENT PRODUCT
      // =====================================================

      localStorage.setItem(
        "forgeintel_generated_product",
        JSON.stringify(generatedIntelligence)
      );


      // =====================================================
      // UPDATE STATE
      // =====================================================

      setIntelligence(generatedIntelligence);
      setComplete(true);

    }, processingSteps.length * 900 + 500);


    timers.push(finishTimer);


    // =====================================================
    // CLEANUP TIMERS
    // =====================================================

    return () => {
      timers.forEach(clearTimeout);
    };

  }, [product, navigate]);


  // =====================================================
  // CONTINUE TO PRODUCT DETAILS
  // =====================================================

  const handleContinue = () => {
    if (!intelligence) {
      return;
    }

    navigate(
      `/products/${intelligence.id}`
    );
  };


  // =====================================================
  // RENDER
  // =====================================================

  return (
    <main className="dashboard processing-page">

      <div className="processing-wrapper">


        {/* HEADER */}

        <div className="processing-header">

          <div className="processing-logo">
            <Sparkles size={25} />
          </div>

          <p className="eyebrow">
            FORGEINTEL ENGINE
          </p>

          <h1>
            Building Product Intelligence
          </h1>

          <p>
            Analyzing available information for{" "}
            <strong>
              {product?.name}
            </strong>
          </p>

        </div>


        {/* PROCESSING CARD */}

        <section className="content-card processing-card">


          {/* PROGRESS */}

          <div className="processing-progress">

            <div className="processing-progress-bar">

              <div
                style={{
                  width: `${Math.min(
                    (currentStep /
                      processingSteps.length) *
                      100,
                    100
                  )}%`,
                }}
              />

            </div>

            <span>
              {complete
                ? "Processing complete"
                : `${currentStep} of ${processingSteps.length} stages`}
            </span>

          </div>


          {/* PROCESSING STEPS */}

          <div className="processing-steps">

            {processingSteps.map((step) => {

              const Icon = step.icon;

              const isComplete =
                complete ||
                currentStep > step.id;

              const isCurrent =
                !complete &&
                currentStep === step.id;


              return (
                <div
                  key={step.id}
                  className={`processing-step ${
                    isComplete
                      ? "step-complete"
                      : isCurrent
                      ? "step-current"
                      : ""
                  }`}
                >

                  <div className="step-icon">

                    {isComplete ? (

                      <CheckCircle2 size={19} />

                    ) : isCurrent ? (

                      <LoaderCircle
                        size={19}
                        className="spin"
                      />

                    ) : (

                      <Icon size={19} />

                    )}

                  </div>


                  <div className="step-content">

                    <strong>
                      {step.title}
                    </strong>

                    <p>
                      {step.description}
                    </p>

                  </div>


                  <div className="step-status">

                    {isComplete
                      ? "Complete"
                      : isCurrent
                      ? "Processing"
                      : "Waiting"}

                  </div>

                </div>
              );
            })}

          </div>


          {/* COMPLETE */}

          {complete && intelligence && (

            <div className="processing-complete">

              <div className="complete-icon">
                <CheckCircle2 size={28} />
              </div>


              <div>

                <strong>
                  Product intelligence generated
                </strong>

                <p>
                  ForgeIntel has completed extraction,
                  enrichment and validation and saved
                  the product intelligence.
                </p>

              </div>


              <button
                type="button"
                onClick={handleContinue}
                className="generate-button"
              >
                View Intelligence
                <ArrowRight size={17} />
              </button>

            </div>

          )}

        </section>

      </div>

    </main>
  );
}


export default Processing;